# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
THUMB_SIZE: 32
SMALL_SIZE: 64
MEDIUM_SIZE: 100
FEE_RATE: 0.05
FEE_STATIC: 0.30
# In seconds
CHAT_LIMIT: 1
CHAT_POLLING: 5

CHAT_MSG_PER_PAGE: 10

GMAIL_DOMAIN: austingulati.com
GMAIL_USERNAME: noreply@austingulati.com
GMAIL_PASSWORD: U6Cq7j*L!!