# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
THUMB_SIZE: 32
SMALL_SIZE: 64
MEDIUM_SIZE: 100
LARGE_SIZE: 210
FULL_SIZE: 500
FEE_RATE: 0.05
PAYPAL_FEE_RATE: 0.029
FEE_STATIC: 0.30
PAYPAL_FEE_STATIC: 0.30
CHAT_LIMIT: 1
CHAT_MSG_PER_PAGE: 15

# In milliseconds
CHAT_LIMIT: 1000
CHAT_POLLING: 5000

GMAIL_DOMAIN: paywith.me
GMAIL_USERNAME: noreply@paywith.me
GMAIL_PASSWORD: U6Cq7j*L!!

SENDGRID_DOMAIN: paywith.me
SENDGRID_USERNAME: paywithme
SENDGRID_PASSWORD: 1Wearesocool

PAYPAL_EMAIL: schonj2@rpi.edu
PAYPAL_USERNAME: schonj2_api1.rpi.edu
PAYPAL_PASSWORD: CA9482TX8CPJ5CJG
PAYPAL_SIGNATURE: AFcWxV21C7fd0v3bYYYRCpSSRl31ANLBuQnoAYBbk05NbtgZ9DAP6YGL
PAYPAL_APPID: APP-5WA6552303474614G

PAYPAL_SANDBOX_EMAIL: pwm_1356895357_biz@austingulati.com
PAYPAL_SANDBOX_USERNAME: pwm_1356895357_biz_api1.austingulati.com
PAYPAL_SANDBOX_PASSWORD: 1356895379
PAYPAL_SANDBOX_SIGNATURE: AFcWxV21C7fd0v3bYYYRCpSSRl31AqS877uwjNHfPGHl7GLUigTo9kjl
PAYPAL_SANDBOX_APPID: APP-80W284485P519543T

WEPAY_SANDBOX_CLIENT_ID: 151353
WEPAY_SANDBOX_CLIENT_SECRET: 24ad3727dd
WEPAY_SANDBOX_ACCESS_TOKEN: STAGE_ebbed7ef921e811c1080572c0c75777f2d3d9a8f32b025656a249671ab7a7d28

WEPAY_CLIENT_ID: 172361
WEPAY_CLIENT_SECRET: d7a7a968b0
WEPAY_ACCESS_TOKEN: PRODUCTION_47fa4bf7178a21e29264f47b600264f511d76e53f04ea67585493c2b2459c5ae

DWOLLA_KEY: XV7LXC7tu3NlVe8qFcwKVJCIp9AmEzIXHUC2P6QOwu06H3i3Om
DWOLLA_SECRET_KEY: U34SfFeKCYWvJ/xJzOJDW1iDlAgeZ/FXqkUepevRFdDvAaT7XO

RACKSPACE_KEY: 441e6ae0fb2aa44eb6c81af9cfc8a7bb
RACKSPACE_USERNAME: paywithme
RACKSPACE_URL: storage101.ord1.clouddrive.com

NUDGE_LIMIT: 3